### PR TITLE
Reformat text: divide by paragraphs

### PR DESCRIPTION
**Pull request by bocharsky-bw**
Usually, a string which length more than 80 characters move to the next line for readability.

Btw, my favorite online MarkDown editor is https://stackedit.io . It has nice examples :)

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Ping @OleksiiRudyi ! Try to merge my PR :)

**Comment by bocharsky-bw** [comment]
Yay, you did it! :)

**Comment by OleksiiRudyi** [comment]
@bocharsky-bw 
 Awesome! Thanks)

**Comment by bocharsky-bw** [comment]
@OleksiiRudyi You did a big step towards Open Source (OS) projects ;)

**Pull request merged**
